[3.2.0] Add simplified setup for WSO2 API Manager
wso2/kubernetes-apim pull request #429
Opened 2020-08-05 17:47 UTC by ThilinaManamgoda

## Purpose
> This PR introduces the Simplified setup for WSO2 API Manager version 3.2.0. This Fixes #428. 
Tested with, 
>- Analytics Dashboard `3.2.0-RC1`
>- All the other component `3.2.0-beta` 

## Goals
> Introduces Simplified setup for WSO2 API Manager version 3.2.0

## Test environment
>GKE based Kubernetes Server version: 1.15.12-gke.2

2020-08-05 18:34 UTC, chirangaalwis commented
@ThilinaManamgoda the PR LGTM!

As per the product team, the `RC-2` release is expected to happen soon. Let's finalize everything using the same release (both APIM and APIM Analytics) and merge this.

2020-08-06 06:47 UTC, ThilinaManamgoda commented
> @ThilinaManamgoda the PR LGTM!
> 
> As per the product team, the `RC-2` release is expected to happen soon. Let's finalize everything using the same release (both APIM and APIM Analytics) and merge this.

ACK

2020-08-25 06:46 UTC, ThilinaManamgoda commented
> > @ThilinaManamgoda the PR LGTM!
> > As per the product team, the `RC-2` release is expected to happen soon. Let's finalize everything using the same release (both APIM and APIM Analytics) and merge this.
> 
> ACK

Teste with RC6 distributions. This PR also address fixes #329

2020-08-25 07:23 UTC, chirangaalwis requested changes

2020-08-25 07:23 UTC, chirangaalwis commented on simple/README.md
> +* WSO2 subscribed users can run [wso2am-latest.sh](https://github.com/wso2/kubernetes-apim/blob/3.2.x/simple/deployment-scripts/wso2am-latest.sh) with the latest updates by providing their subscripti
@ThilinaManamgoda the word `referring` is not spelled correctly, here.

2020-08-25 07:23 UTC, chirangaalwis commented on simple/README.md
> + This artifact doesn't support [Docker Desktop](https://www.docker.com/products/docker-desktop).
@ThilinaManamgoda shall we add this as a note, as follows?

> This artifact doesn't support [Docker Desktop](https://www.docker.com/products/docker-desktop).

2020-08-25 07:24 UTC, chirangaalwis commented on simple/README.md
> +* WSO2 subscribed users can run [wso2am-latest.sh](https://github.com/wso2/kubernetes-apim/blob/3.2.x/simple/deployment-scripts/wso2am-latest.sh) with the latest updates by providing their subscripti
@ThilinaManamgoda also it has to be `Further users can acquire a subscription by referring to this [link](https://wso2.com/subscription).`

2020-08-25 07:40 UTC, chirangaalwis approved these changes

2020-08-25 07:41 UTC, merged